import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { ArrowRight, User as UserIcon, Lock, Mail, Phone, CheckCircle } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { AuthService } from '../../services/authService';
import { CourseService } from '../../services/courseService';
import { formatPhoneNumber } from '../../utils/formatters';

export const RegisterPage = () => {
    const navigate = useNavigate();
    const [formData, setFormData] = useState({
        name: '',
        email: '',
        phone: '',
        password: '',
        confirmPassword: '',
        selectedCourses: [] as string[] // ⭐️ 변경: 다중 선택 배열
    });
    const [error, setError] = useState('');
    const [courses, setCourses] = useState<string[]>([]);

    const [role, setRole] = useState<'student' | 'admin'>('student');

    // Load courses
    useEffect(() => {
        const loadCourses = async () => {
            try {
                const courseList = await CourseService.getCourses();
                const courseNames = courseList.map((c: any) => c.name);
                setCourses(courseNames);
            } catch (err) {
                console.error('Failed to load courses', err);
            }
        };
        loadCourses();
    }, []);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setError('');

        // 필수 필드 검증
        if (!formData.email || !formData.password || !formData.name || !formData.phone) {
            setError('모든 필수 항목을 입력해주세요.');
            return;
        }

        // 비밀번호 확인 검증
        if (!formData.confirmPassword) {
            setError('비밀번호 확인을 입력해주세요.');
            return;
        }

        if (formData.password !== formData.confirmPassword) {
            setError('비밀번호가 일치하지 않습니다.');
            return;
        }

        const isPasswordValid = formData.password.length >= 8 &&
            /\d/.test(formData.password) &&
            /[!@#$%^&*(),.?":{}|<>]/.test(formData.password);

        if (!isPasswordValid) {
            setError('비밀번호는 8자 이상이어야 하며, 숫자와 특수문자를 포함해야 합니다.');
            return;
        }

        // 수강생인 경우 과정 선택 필수
        try {
            const result = await AuthService.register({
                id: '', // Generated by service
                email: formData.email,
                password: formData.password,
                name: formData.name,
                phone: formData.phone,
                role: role,
                createdAt: '', // Generated by service
                courseEnrollments: formData.selectedCourses.map(c => ({
                    courseName: c,
                    enrolledAt: new Date().toISOString(),
                    status: 'pending'
                }))
            });
            if (result.success) {
                const message = role === 'student'
                    ? '회원가입이 완료되었습니다!\n\n로그인 후 대시보드에 바로 접속하실 수 있습니다.\n선택하신 과정은 관리자 승인 후 문제를 풀 수 있습니다.'
                    : '회원가입 요청이 완료되었습니다.\n\n관리자 승인 후 로그인하실 수 있습니다.';
                alert(message);
                navigate('/login');
            } else {
                setError(result.message || '회원가입 실패');
            }
        } catch (err) {
            setError('오류가 발생했습니다.');
        }
    };

    return (
        // Outer container with padding for mobile scroll support
        <div style={{ minHeight: '100vh', width: '100%', background: 'var(--slate-50)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '1rem' }}>
            {/* Same container styles */}
            <div className="grid-cols-2" style={{
                width: '100%', maxWidth: '1200px',
                minHeight: '600px', // Ensure reasonable height on desktop
                boxShadow: 'var(--shadow-2xl)', borderRadius: '1.5rem', overflow: 'hidden', background: 'white',
                display: 'grid'
            }}>

                {/* Left: Visuals as is */}
                <div style={{
                    background: 'linear-gradient(180deg, #020617 0%, #172554 100%)',
                    position: 'relative',
                    padding: '3rem',
                    display: 'flex',
                    flexDirection: 'column',
                    justifyContent: 'center',
                    alignItems: 'center',
                    color: 'white',
                    textAlign: 'center'
                }}>
                    <div style={{ position: 'relative', zIndex: 1, width: '100%', maxWidth: '380px' }}>
                        <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.8 }}>
                            {/* Logo Area */}
                            <div style={{ marginBottom: '2.5rem' }}>
                                <img src="/images/wow_logo.png" alt="WOW3D-CBT" style={{ height: '60px', filter: 'brightness(0) invert(1)' }} />
                            </div>

                            <h1 style={{ fontSize: '1.8rem', lineHeight: 1.3, marginBottom: '2rem', color: 'white', fontWeight: 700 }}>
                                WOW3D-CBT(문제은행)<br />서비스
                            </h1>
                            <p style={{ fontSize: '1rem', color: 'var(--slate-300)', marginBottom: '2rem' }}>
                                지금 가입하고 실전 모의고사와 오답 노트를<br />무료로 이용해보세요.
                            </p>
                        </motion.div>
                    </div>
                </div>

                {/* Right: Register Form */}
                <div style={{ padding: '4rem', display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
                    <div style={{ maxWidth: '400px', width: '100%', margin: '0 auto' }}>
                        <div style={{ marginBottom: '2rem' }}>
                            <h2 style={{ fontSize: '2.5rem', marginBottom: '1rem', fontWeight: 800 }}>회원가입 🚀</h2>
                            <p style={{ color: 'var(--text-muted)', fontSize: '1.2rem' }}>
                                이미 계정이 있으신가요? <a onClick={() => navigate('/login')} style={{ color: 'var(--primary-600)', fontWeight: 700, cursor: 'pointer', fontSize: '1.3rem', marginLeft: '0.5rem' }}>로그인하기</a>
                            </p>
                        </div>

                        {error && <div style={{ background: '#fef2f2', color: '#dc2626', padding: '0.75rem', borderRadius: '0.5rem', marginBottom: '1rem', fontSize: '0.9rem' }}>{error}</div>}

                        {/* Role Switcher */}
                        <div style={{ background: 'var(--slate-100)', padding: '0.25rem', borderRadius: '0.5rem', display: 'flex', marginBottom: '1.5rem' }}>
                            <button
                                type="button"
                                style={{
                                    flex: 1, padding: '0.5rem', borderRadius: '0.375rem', fontSize: '0.875rem', fontWeight: 500,
                                    background: role === 'student' ? 'white' : 'transparent',
                                    color: role === 'student' ? 'var(--slate-900)' : 'var(--slate-500)',
                                    boxShadow: role === 'student' ? '0 1px 2px 0 rgb(0 0 0 / 0.05)' : 'none',
                                    transition: 'all 0.2s'
                                }}
                                onClick={() => setRole('student')}
                            >
                                수강생
                            </button>
                            <button
                                type="button"
                                style={{
                                    flex: 1, padding: '0.5rem', borderRadius: '0.375rem', fontSize: '0.875rem', fontWeight: 500,
                                    background: role === 'admin' ? 'white' : 'transparent',
                                    color: role === 'admin' ? 'var(--slate-900)' : 'var(--slate-500)',
                                    boxShadow: role === 'admin' ? '0 1px 2px 0 rgb(0 0 0 / 0.05)' : 'none',
                                    transition: 'all 0.2s'
                                }}
                                onClick={() => setRole('admin')}
                            >
                                관리자
                            </button>
                        </div>
                        {role === 'admin' && (
                            <div style={{ padding: '0.75rem', background: '#fff7ed', borderRadius: '0.5rem', border: '1px solid #fed7aa', marginTop: '0.5rem' }}>
                                <div style={{ fontSize: '0.85rem', color: '#ea580c', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                                    ⚠️ 관리자 계정은 가입 후 승인 대기 상태가 됩니다.
                                </div>
                            </div>
                        )}

                        <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '0.6rem' }}>
                            <div className="input-group" style={{ marginBottom: 0 }}>
                                <label className="input-label">이름</label>
                                <div style={{ position: 'relative' }}>
                                    <UserIcon size={20} style={{ position: 'absolute', left: '1rem', top: '50%', transform: 'translateY(-50%)', color: 'var(--slate-400)' }} />
                                    <input
                                        type="text"
                                        name="name"
                                        autoComplete="name"
                                        className="input-field"
                                        placeholder="홍길동"
                                        style={{ paddingLeft: '3rem' }}
                                        required
                                        value={formData.name}
                                        onChange={e => setFormData({ ...formData, name: e.target.value })}
                                    />
                                </div>
                            </div>

                            <div className="input-group" style={{ marginBottom: 0 }}>
                                <label className="input-label">이메일</label>
                                <div style={{ position: 'relative' }}>
                                    <Mail size={20} style={{ position: 'absolute', left: '1rem', top: '50%', transform: 'translateY(-50%)', color: 'var(--slate-400)' }} />
                                    <input
                                        type="email"
                                        name="email"
                                        autoComplete="email"
                                        className="input-field"
                                        placeholder="name@example.com"
                                        style={{ paddingLeft: '3rem' }}
                                        required
                                        value={formData.email}
                                        onChange={e => setFormData({ ...formData, email: e.target.value })}
                                    />
                                </div>
                            </div>

                            <div className="input-group" style={{ marginBottom: 0 }}>
                                <label className="input-label">전화번호</label>
                                <div style={{ position: 'relative' }}>
                                    <Phone size={20} style={{ position: 'absolute', left: '1rem', top: '50%', transform: 'translateY(-50%)', color: 'var(--slate-400)' }} />
                                    <input
                                        type="tel"
                                        name="phone"
                                        autoComplete="tel"
                                        className="input-field"
                                        placeholder="010-1234-5678"
                                        style={{ paddingLeft: '3rem' }}
                                        required
                                        value={formData.phone}
                                        onChange={e => setFormData({ ...formData, phone: formatPhoneNumber(e.target.value) })}
                                    />
                                </div>
                            </div>

                            <div className="input-group" style={{ marginBottom: 0 }}>
                                <label className="input-label">비밀번호</label>
                                <div style={{ position: 'relative' }}>
                                    <Lock size={20} style={{ position: 'absolute', left: '1rem', top: '50%', transform: 'translateY(-50%)', color: 'var(--slate-400)' }} />
                                    <input
                                        type="password"
                                        name="password"
                                        autoComplete="new-password"
                                        className="input-field"
                                        placeholder="********"
                                        style={{ paddingLeft: '3rem' }}
                                        required
                                        value={formData.password}
                                        onChange={e => setFormData({ ...formData, password: e.target.value })}
                                    />
                                </div>
                            </div>
                            <div style={{ marginTop: '0.5rem', display: 'flex', gap: '0.75rem' }}>
                                <PasswordCheck label="8자 이상" isValid={formData.password.length >= 8} />
                                <PasswordCheck label="숫자 포함" isValid={/\d/.test(formData.password)} />
                                <PasswordCheck label="특수문자 포함" isValid={/[!@#$%^&*(),.?":{}|<>]/.test(formData.password)} />
                            </div>

                            <div className="input-group" style={{ marginBottom: 0 }}>
                                <label className="input-label">비밀번호 확인</label>
                                <div style={{ position: 'relative' }}>
                                    <Lock size={20} style={{ position: 'absolute', left: '1rem', top: '50%', transform: 'translateY(-50%)', color: 'var(--slate-400)' }} />
                                    <input
                                        type="password"
                                        name="confirmPassword"
                                        autoComplete="new-password"
                                        className="input-field"
                                        placeholder="********"
                                        style={{ paddingLeft: '3rem' }}
                                        required
                                        value={formData.confirmPassword}
                                        onChange={e => setFormData({ ...formData, confirmPassword: e.target.value })}
                                    />
                                </div>
                            </div>

                            {/* ⭐️ 과정 선택 (수강생만) */}
                            {/* ⭐️ 과정 선택 (수강생만) - 다중 선택 & 선택 사항 */}
                            {role === 'student' && (
                                <div className="input-group" style={{ marginBottom: 0 }}>
                                    <label className="input-label">수강과정 및 시험 선택 (복수 선택 가능)</label>
                                    <div style={{
                                        display: 'flex', flexDirection: 'column', gap: '0.5rem',
                                        maxHeight: '200px', overflowY: 'auto',
                                        border: '1px solid #e2e8f0', borderRadius: '0.5rem',
                                        padding: '0.75rem', background: '#f8fafc'
                                    }}>
                                        {courses.length > 0 ? courses.map(course => (
                                            <label key={course} style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', cursor: 'pointer', fontSize: '0.9rem', color: '#334155' }}>
                                                <input
                                                    type="checkbox"
                                                    checked={formData.selectedCourses.includes(course)}
                                                    onChange={(e) => {
                                                        const newCourses = e.target.checked
                                                            ? [...formData.selectedCourses, course]
                                                            : formData.selectedCourses.filter(c => c !== course);
                                                        setFormData({ ...formData, selectedCourses: newCourses });
                                                    }}
                                                    style={{ width: '1.1rem', height: '1.1rem', accentColor: 'var(--primary-600)', cursor: 'pointer' }}
                                                />
                                                {course}
                                            </label>
                                        )) : (
                                            <div style={{ color: '#94a3b8', fontSize: '0.875rem' }}>등록된 과정이 없습니다.</div>
                                        )}
                                    </div>
                                    <p style={{ fontSize: '0.8rem', color: '#64748b', marginTop: '0.5rem' }}>
                                        💡 선택하지 않아도 가입할 수 있습니다. (추후 신청 가능)
                                    </p>
                                </div>
                            )}

                            <button type="submit" className="btn btn-primary" style={{ marginTop: '1rem' }}>
                                계정 생성하기 <ArrowRight size={18} />
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    );
};

const PasswordCheck = ({ label, isValid }: { label: string, isValid: boolean }) => (
    <div style={{ display: 'flex', alignItems: 'center', gap: '0.25rem', fontSize: '0.75rem', color: isValid ? '#10b981' : '#94a3b8', fontWeight: 500 }}>
        <CheckCircle size={14} color={isValid ? '#10b981' : '#cbd5e1'} strokeWidth={3} />
        <span>{label}</span>
    </div>
);
